name: Android APK (Capacitor)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Prepare web assets (copy to www/)
        run: npm run prepare:www

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses

      - name: Install Android platforms & tools
        run: |
          sdkmanager "platform-tools" || true
          sdkmanager "platforms;android-34" || true
          sdkmanager "build-tools;34.0.0" || true

      - name: Add Android platform (Capacitor)
        run: npx cap add android --yes

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build Debug APK
        run: cd android && chmod +x ./gradlew && ./gradlew assembleDebug --no-daemon

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk

      - name: Build Release APK (unsigned)
        run: cd android && ./gradlew assembleRelease --no-daemon

      - name: Upload Release APK (unsigned)
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          path: android/app/build/outputs/apk/release/app-release-unsigned.apk
